# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d73ea0d669c4faedb0d68d39206f396a2c107bf86fead66575b2429fd8cacf622ce61add3c904d52f7ed841fb1d4d6396fc1d2913056ff972e92903e4dd3bef

test:
  secret_key_base: 37bba58340fe23fc2f9559300783244b00a0504f1a88cb75eafe48ecfba7d71c04cf58353ded4c7d645e936af0b2f8a3f91962edfae384d8f9f1d135852a9ba0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
